[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v -s --tb=short --html=report.html --self-contained-html

markers =
    api:  tests de API
    smoke: marca para tests de humo
    regression: marca para tests de regresión
    critical: marca para tests críticos